### ISSUE TITLE
viterbi?

### ISSUE THREAD

**Issue by tbeason** [JuliaStats/HiddenMarkovModels.jl#1]
How difficult would it be to implement the viterbi pass? I see it was present in HMMBase: https://github.com/maxmouchet/HMMBase.jl/blob/master/src/viterbi.jl

**Comment by gdalle** [comment]
Hi! This package is indeed meant to be the successor of HMMBase but I haven't been able to give it much time lately. I'll try to get back to it soon, Viterbi is definitely on the list

**Comment by tbeason** [comment]
Well, good news. It is not hard to get something working. It is not super flexible (e.g. not AD friendly) but it works. Modifying that file, you need to `import Base.OneTo` and `using HiddenMarkovModels: loglikelihoods` and then this should "just work". No idea if correct.

```
function viterbilog!(
    T1::AbstractMatrix,
    T2::AbstractMatrix,
    z::AbstractVector,
    a::AbstractVector,
    A::AbstractMatrix,
    LL::AbstractMatrix,
)
    T, K = size(LL)
    (T == 0) && return

    fill!(T1, 0.0)
    fill!(T2, 0)

    al = log.(a)
    Al = log.(A)

    for i in OneTo(K)
        T1[1, i] = al[i] + LL[1, i]
    end

    @inbounds for t = 2:T
        for j in OneTo(K)
            amax = 0
            vmax = -Inf

            for i in OneTo(K)
                v = T1[t-1, i] + Al[i, j]
                if v > vmax
                    amax = i
                    vmax = v
                end
            end

            T1[t, j] = vmax + LL[t, j]
            T2[t, j] = amax
        end
    end

    z[T] = argmax(T1[T, :])
    for t = T-1:-1:1
        z[t] = T2[t+1, z[t+1]]
    end
end


function viterbi(a::AbstractVector, A::AbstractMatrix, LL::AbstractMatrix)

    T1 = Matrix{Float64}(undef, size(LL))
    T2 = Matrix{Int}(undef, size(LL))
    z = Vector{Int}(undef, size(LL, 1))
    viterbilog!(T1, T2, z, a, A, LL)
    z
end


function viterbi(hmm::AbstractHMM, θ, observations)
    LL = loglikelihoods(hmm, θ, observations)'
    viterbi(hmm.initial_distribution, hmm.transition_matrix, LL)
end
```

**Comment by gdalle** [comment]
Cool, thanks! No promises but if I have some time this weekend I'll try to make a pass and add it

**Comment by gdalle** [comment]
@tbeason closing this because viterbi is now implemented and tested against the HMMBase version, so it should work! The package is not yet registered but I gave it a significant push this week, feel free to play around :)
