### ISSUE TITLE
HDP priors?

### ISSUE THREAD

**Issue by rsenne** [JuliaStats/HiddenMarkovModels.jl#118]
Heya @gdalle! Was wondering if you had been thinking about implementing the ["Infinite Hidden Markov Model"](https://mlg.eng.cam.ac.uk/zoubin/papers/ihmm.pdf)? I was planning on adding this modeling structure to StateSpaceDynamics.jl soon, but since collaboration seems imminent, if this wasn't already a direction you had, I might try implementing this into HiddenMarkovModels.jl in the near-ish future.

**Comment by gdalle** [comment]
Hi @rsenne, thank you for the suggestion.
I had never read that paper before. I took a quick look and it seems to employ very different estimation algorithms (not exact but approximate), which means the overlap with HiddenMarkovModels.jl is rather low. I think this would make more sense in a separate package like InfiniteHiddenMarkovModels.jl, which could of course depend on mine for anything it needs.
