### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by gdalle** [JuliaStats/HiddenMarkovModels.jl#2]
Compare with competitors on the efficiency of the 3 main algorithms (forward, Viterbi, Baum-Welch):
- https://github.com/maxmouchet/HMMBase.jl
- https://github.com/hmmlearn/hmmlearn
- https://github.com/jmschrei/pomegranate

Scenarios:
- dense / sparse
- log / not log

**Comment by tbeason** [comment]
seqHMM R package might also be a worthy competitor? That is what I was using previously (via RCall)

https://github.com/helske/seqHMM

They say 

> Maximum likelihood estimation via EM algorithm and direct numerical maximization with analytical gradients is supported. All main algorithms are written in C++ with parallel computation support via OpenMP.

**Comment by gdalle** [comment]
Unfortunately I don't know how to write R code ^^

Besides, I'm a little wary of benchmarking through an interface package like PythonCall or RCall. That is why, for my current benchmarks, the Python timings are measured from within Python itself.

If you want to submit a PR doing the same with seqHMM, I can't promise I'll merge but at least I'll study it!
From what I gather it only does categorical observations? Is that your primary use case? I could also add those to the benchmark sets.

**Comment by tbeason** [comment]
> From what I gather it only does categorical observations? Is that your primary use case?

Yes to both, although I expect I could use this in the future for other purposes as well.

**Comment by gdalle** [comment]
Mostly solved for Python competitors, including the brand new `dynamax` (see upcoming JOSS paper)
