### ISSUE TITLE
Make modification to allow support for Heterogeneous (Periodic) Hidden Markov Models

### ISSUE THREAD

**Issue by dmetivie** [JuliaStats/HiddenMarkovModels.jl#52]
As we discussed, that would be nice (when you have time) to make the changes to allow support of time dependent HMMs (transition matrices + emission distribution) is possible. 
Then, check that these changes do not affect the performances of homogeneous HMMs.

**Comment by gdalle** [comment]
Done on the main branch, awaiting feedback before tagging release
