### ISSUE TITLE
Clarify docs on the arguments of `fit!`

### ISSUE THREAD

**Issue by cossio** [JuliaStats/HiddenMarkovModels.jl#53]
Opening issue at the request of Guillaume Dalle.

Make the docs of `fit!` explicit on the types of arguments `obs_seq`, `trans_count`, etc.

> Essentially `obs_seq` is the concatenation of all observation sequences so it’s a vector
> And `trans_count` is an NxN matrix

**Comment by gdalle** [comment]
Done in the main branch
